name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-
      - name: Install PHP dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=phpcs.xml.dist
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install JavaScript dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint . --ext .js
      - name: Run Jest
        run: npm test
